---
apiVersion: v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/no-provisioner
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adrion-postgres-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  hostPath:
    path: "/data/adrion/postgres"
    type: DirectoryOrCreate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: adrion
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 50Gi
