apiVersion: 1

contactPoints:
  - orgId: 1
    name: adrion-webhook
    receivers:
      - uid: adrion-webhook-receiver
        type: webhook
        settings:
          url: ${GRAFANA_ALERT_WEBHOOK_URL}
          httpMethod: POST
          maxAlerts: 0
          title: ADRION Alert
          message: '{{ template "default.message" . }}'
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: adrion-webhook
    group_by:
      - alertname
      - severity
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
